// Turns the game page into web/game.ts, the version that ships inside the app:
//   • developer tools off (DEV=false), so testing buttons and sample leaderboard players never ship
//   • Google Fonts replaced by the bundled Fredoka font, embedded in the page, so it works offline
// Usage: node scripts/build-web.mjs web/critter-stack.html
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = process.argv[2] || join(root, 'web/critter-stack.html');
let html = readFileSync(src, 'utf8');

const devCount = (html.match(/const DEV=true/g) || []).length;
if (devCount !== 1) throw new Error(`expected exactly one "const DEV=true", found ${devCount}`);
html = html.replace('const DEV=true', 'const DEV=false');

html = html.replace(/<link rel="(?:preconnect|stylesheet)" href="https:\/\/fonts\.[^>]*>\n?/g, '');
const fontPath = join(root, 'web/Fredoka.ttf');
let font = null;
try { const buf = readFileSync(fontPath); if (buf.length > 20000) font = buf.toString('base64'); } catch {}
if (font) {
  html = html.replace('<style>', `<style>@font-face{font-family:"Fredoka";src:url(data:font/ttf;base64,${font}) format("truetype");font-weight:300 700;font-display:block}\n`);
} else if (process.env.EAS_BUILD) {
  throw new Error('web/Fredoka.ttf is missing: the EAS post-install step should have downloaded it');
} else {
  console.warn('web/Fredoka.ttf not found: this local build falls back to the system font');
}

if (/fonts\.googleapis|fonts\.gstatic/.test(html)) throw new Error('a Google Fonts link is still in the page');
writeFileSync(join(root, 'web/game.ts'), `// Generated by scripts/build-web.mjs from web/critter-stack.html. Do not edit by hand.\nconst GAME_HTML: string = ${JSON.stringify(html)};\nexport default GAME_HTML;\n`);
console.log(`web/game.ts written (${Math.round(html.length / 1024)} KB)`);
